// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperHero.Models;

namespace apiforcapstone.Migrations
{
    [DbContext(typeof(SuperHeroContext))]
    [Migration("20220228000628_Characters")]
    partial class Characters
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SuperHero.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Combat")
                        .HasColumnType("int");

                    b.Property<int>("Durability")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<string>("SecretID")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            Combat = 30,
                            Durability = 85,
                            Intelligence = 90,
                            Name = "Raven",
                            Power = 92,
                            SecretID = "Raven",
                            Speed = 62,
                            Strength = 50
                        },
                        new
                        {
                            CharacterId = 2,
                            Combat = 50,
                            Durability = 70,
                            Intelligence = 55,
                            Name = "Human Torch",
                            Power = 81,
                            SecretID = "Johnny Storm",
                            Speed = 87,
                            Strength = 70
                        },
                        new
                        {
                            CharacterId = 3,
                            Combat = 50,
                            Durability = 40,
                            Intelligence = 96,
                            Name = "Dr Strange",
                            Power = 99,
                            SecretID = "Stephen Strange",
                            Speed = 76,
                            Strength = 80
                        },
                        new
                        {
                            CharacterId = 4,
                            Combat = 89,
                            Durability = 87,
                            Intelligence = 87,
                            Name = "Spider Man 2099",
                            Power = 45,
                            SecretID = "Miguel O'Hara",
                            Speed = 77,
                            Strength = 88
                        },
                        new
                        {
                            CharacterId = 5,
                            Combat = 95,
                            Durability = 40,
                            Intelligence = 50,
                            Name = "Green Arrow",
                            Power = 20,
                            SecretID = "Oliver Queen",
                            Speed = 48,
                            Strength = 60
                        },
                        new
                        {
                            CharacterId = 6,
                            Combat = 68,
                            Durability = 66,
                            Intelligence = 78,
                            Name = "Zatanna",
                            Power = 89,
                            SecretID = "Zatanna Zatara",
                            Speed = 50,
                            Strength = 58
                        },
                        new
                        {
                            CharacterId = 7,
                            Combat = 84,
                            Durability = 60,
                            Intelligence = 80,
                            Name = "Capt. of Heart Pirates",
                            Power = 93,
                            SecretID = "Trafalgar Law",
                            Speed = 35,
                            Strength = 70
                        },
                        new
                        {
                            CharacterId = 8,
                            Combat = 10,
                            Durability = 35,
                            Intelligence = 95,
                            Name = "Yami Yugi",
                            Power = 90,
                            SecretID = "Yami Yugi",
                            Speed = 10,
                            Strength = 40
                        },
                        new
                        {
                            CharacterId = 9,
                            Combat = 85,
                            Durability = 95,
                            Intelligence = 80,
                            Name = "Darth Vader",
                            Power = 94,
                            SecretID = "Anakin Skywalker",
                            Speed = 50,
                            Strength = 90
                        },
                        new
                        {
                            CharacterId = 10,
                            Combat = 84,
                            Durability = 70,
                            Intelligence = 60,
                            Name = "The Last Air Bender",
                            Power = 87,
                            SecretID = "Aang",
                            Speed = 89,
                            Strength = 60
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
