// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperHero.Models;

namespace apiforcapstone.Migrations
{
    [DbContext(typeof(SuperHeroContext))]
    [Migration("20220312051822_Characterss")]
    partial class Characterss
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SuperHero.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Combat")
                        .HasColumnType("int");

                    b.Property<int>("Durability")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<string>("SecretID")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            Combat = 30,
                            Durability = 85,
                            Intelligence = 90,
                            Name = "Raven",
                            Power = 92,
                            SecretID = "Raven",
                            Speed = 62,
                            Strength = 50
                        },
                        new
                        {
                            CharacterId = 2,
                            Combat = 50,
                            Durability = 70,
                            Intelligence = 55,
                            Name = "Human Torch",
                            Power = 81,
                            SecretID = "Johnny Storm",
                            Speed = 87,
                            Strength = 70
                        },
                        new
                        {
                            CharacterId = 3,
                            Combat = 50,
                            Durability = 40,
                            Intelligence = 96,
                            Name = "Dr Strange",
                            Power = 99,
                            SecretID = "Stephen Strange",
                            Speed = 76,
                            Strength = 80
                        },
                        new
                        {
                            CharacterId = 4,
                            Combat = 89,
                            Durability = 87,
                            Intelligence = 87,
                            Name = "Spider Man 2099",
                            Power = 45,
                            SecretID = "Miguel O'Hara",
                            Speed = 77,
                            Strength = 88
                        },
                        new
                        {
                            CharacterId = 5,
                            Combat = 95,
                            Durability = 40,
                            Intelligence = 50,
                            Name = "Green Arrow",
                            Power = 20,
                            SecretID = "Oliver Queen",
                            Speed = 48,
                            Strength = 60
                        },
                        new
                        {
                            CharacterId = 6,
                            Combat = 68,
                            Durability = 66,
                            Intelligence = 78,
                            Name = "Zatanna",
                            Power = 89,
                            SecretID = "Zatanna Zatara",
                            Speed = 50,
                            Strength = 58
                        },
                        new
                        {
                            CharacterId = 7,
                            Combat = 84,
                            Durability = 60,
                            Intelligence = 80,
                            Name = "Capt. of Heart Pirates",
                            Power = 93,
                            SecretID = "Trafalgar Law",
                            Speed = 35,
                            Strength = 70
                        },
                        new
                        {
                            CharacterId = 8,
                            Combat = 10,
                            Durability = 35,
                            Intelligence = 95,
                            Name = "Yami Yugi",
                            Power = 90,
                            SecretID = "Yami Yugi",
                            Speed = 10,
                            Strength = 40
                        },
                        new
                        {
                            CharacterId = 9,
                            Combat = 85,
                            Durability = 95,
                            Intelligence = 80,
                            Name = "Darth Vader",
                            Power = 94,
                            SecretID = "Anakin Skywalker",
                            Speed = 50,
                            Strength = 90
                        },
                        new
                        {
                            CharacterId = 10,
                            Combat = 84,
                            Durability = 70,
                            Intelligence = 60,
                            Name = "The Last Air Bender",
                            Power = 87,
                            SecretID = "Aang",
                            Speed = 89,
                            Strength = 60
                        },
                        new
                        {
                            CharacterId = 11,
                            Combat = 86,
                            Durability = 90,
                            Intelligence = 90,
                            Name = "Spawn",
                            Power = 92,
                            SecretID = "Albert Simmons",
                            Speed = 80,
                            Strength = 76
                        },
                        new
                        {
                            CharacterId = 12,
                            Combat = 83,
                            Durability = 99,
                            Intelligence = 30,
                            Name = "Deadpool",
                            Power = 25,
                            SecretID = "Wade Wilson",
                            Speed = 65,
                            Strength = 80
                        },
                        new
                        {
                            CharacterId = 13,
                            Combat = 60,
                            Durability = 79,
                            Intelligence = 50,
                            Name = "Green Lantern",
                            Power = 93,
                            SecretID = "Hal Jordan",
                            Speed = 70,
                            Strength = 60
                        },
                        new
                        {
                            CharacterId = 14,
                            Combat = 30,
                            Durability = 60,
                            Intelligence = 99,
                            Name = "Professor X",
                            Power = 94,
                            SecretID = "Charles Xavier",
                            Speed = 1,
                            Strength = 86
                        },
                        new
                        {
                            CharacterId = 15,
                            Combat = 60,
                            Durability = 89,
                            Intelligence = 94,
                            Name = "Dr.Doom",
                            Power = 93,
                            SecretID = "Victor Von Doom",
                            Speed = 30,
                            Strength = 70
                        },
                        new
                        {
                            CharacterId = 16,
                            Combat = 70,
                            Durability = 70,
                            Intelligence = 70,
                            Name = "Master Chief",
                            Power = 70,
                            SecretID = "John 117",
                            Speed = 70,
                            Strength = 70
                        },
                        new
                        {
                            CharacterId = 17,
                            Combat = 35,
                            Durability = 35,
                            Intelligence = 35,
                            Name = "Unenlightened",
                            Power = 35,
                            SecretID = "Amerik Velasquez",
                            Speed = 35,
                            Strength = 35
                        },
                        new
                        {
                            CharacterId = 18,
                            Combat = 80,
                            Durability = 80,
                            Intelligence = 80,
                            Name = "Enlightened Apprentice",
                            Power = 80,
                            SecretID = "Shaun Kent",
                            Speed = 80,
                            Strength = 80
                        },
                        new
                        {
                            CharacterId = 19,
                            Combat = 100,
                            Durability = 100,
                            Intelligence = 100,
                            Name = "The Enlightened One",
                            Power = 100,
                            SecretID = "Andre Velasquez",
                            Speed = 100,
                            Strength = 100
                        },
                        new
                        {
                            CharacterId = 20,
                            Combat = 90,
                            Durability = 99,
                            Intelligence = 40,
                            Name = "Wolverine",
                            Power = 80,
                            SecretID = "James Howlett",
                            Speed = 70,
                            Strength = 90
                        },
                        new
                        {
                            CharacterId = 21,
                            Combat = 97,
                            Durability = 94,
                            Intelligence = 70,
                            Name = "Super Man",
                            Power = 95,
                            SecretID = "Clark Kent",
                            Speed = 90,
                            Strength = 98
                        },
                        new
                        {
                            CharacterId = 22,
                            Combat = 70,
                            Durability = 91,
                            Intelligence = 80,
                            Name = "Pain",
                            Power = 92,
                            SecretID = "Nagato Uzumaki",
                            Speed = 60,
                            Strength = 80
                        },
                        new
                        {
                            CharacterId = 23,
                            Combat = 0,
                            Durability = 99,
                            Intelligence = 0,
                            Name = "console.log",
                            Power = 99,
                            SecretID = "Microsoft Documentation",
                            Speed = 0,
                            Strength = 99
                        },
                        new
                        {
                            CharacterId = 24,
                            Combat = 70,
                            Durability = 67,
                            Intelligence = 86,
                            Name = "Psylocke",
                            Power = 80,
                            SecretID = "Betsy Braddock",
                            Speed = 68,
                            Strength = 79
                        },
                        new
                        {
                            CharacterId = 25,
                            Combat = 78,
                            Durability = 74,
                            Intelligence = 78,
                            Name = "Kingpin",
                            Power = 80,
                            SecretID = "Wilson Fisk",
                            Speed = 40,
                            Strength = 84
                        },
                        new
                        {
                            CharacterId = 26,
                            Combat = 70,
                            Durability = 86,
                            Intelligence = 80,
                            Name = "Dani Moonstar",
                            Power = 89,
                            SecretID = "Dani Moonstar",
                            Speed = 80,
                            Strength = 80
                        },
                        new
                        {
                            CharacterId = 27,
                            Combat = 87,
                            Durability = 77,
                            Intelligence = 80,
                            Name = "Darth Maul",
                            Power = 87,
                            SecretID = "Maul",
                            Speed = 80,
                            Strength = 78
                        },
                        new
                        {
                            CharacterId = 28,
                            Combat = 84,
                            Durability = 60,
                            Intelligence = 96,
                            Name = "Spider-Man",
                            Power = 87,
                            SecretID = "Peter Parker",
                            Speed = 89,
                            Strength = 83
                        },
                        new
                        {
                            CharacterId = 29,
                            Combat = 94,
                            Durability = 95,
                            Intelligence = 50,
                            Name = "Darkseid",
                            Power = 90,
                            SecretID = "Uxas",
                            Speed = 70,
                            Strength = 89
                        },
                        new
                        {
                            CharacterId = 30,
                            Combat = 99,
                            Durability = 99,
                            Intelligence = 99,
                            Name = "Exodia Kanye",
                            Power = 99,
                            SecretID = "Kanye West",
                            Speed = 99,
                            Strength = 99
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
